.TH copen 1 "2024-03-28" "copen" "User Commands"
.\" --------------------------------------------------------------------
.SH NAME
copen \- run command associated with a extension
.\" --------------------------------------------------------------------
.SH SYNOPSIS
\fBcopen\fP <path-to-file>
.\" --------------------------------------------------------------------
.SH DESCRIPTION
Matches file's extension with the table in config
and runs the appropriate command if found 
.\" --------------------------------------------------------------------
.SH OPTIONS
There are no command line options.
.\" --------------------------------------------------------------------
.SH CONFIGURATION
The program must be configured by creating a \fIconfig.h\fP file. You
must then recompile the program.
.P
\fIconfig.def.h\fP is distributed along with the source code. It
explains the basic structure and the options that you can use.
.\" --------------------------------------------------------------------
.SH LICENSE
\fBcopen\fP is released under the BSD 3-Clause license.
See the accompanying \fILICENSE\fP file.

